In [16]:
import numpy as np

Check NumPy version.
!!!!! "__" - two "_" 

In [17]:
print(np.__version__)

1.26.4


### NumPy Creating Arrays

**Create an 1D array**

In [18]:
arr1D = np.array([1, 2, 3, 4, 5])

In [19]:
print(arr1D)

[1 2 3 4 5]


**Create a 2D array**

In [20]:
arr2D = np.array([[1, 2, 3], [4, 5, 6]])

In [21]:
print(arr2D)

[[1 2 3]
 [4 5 6]]


**Create a 3D array**

In [22]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [23]:
print(arr3D)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


Check how many dimensions the arrays have:

In [24]:
print(arr1D.ndim)
print(arr2D.ndim)
print(arr3D.ndim)

1
2
3


**Create an array with 5 dimensions**

In [25]:
arr5D = np.array([1, 2, 3], ndmin = 5)

In [26]:
print(arr5D)

[[[[[1 2 3]]]]]


Check dimension

In [27]:
print(arr5D.ndim)

5


### NumPy Array Indexing

In [39]:
arr1D = np.array([1, 2, 3, 4, 5])
print(arr1D[3])

4


**Access 2-D Arrays**

In [40]:
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2D[1, 1])

5


**Access 3-D Arrays**

In [41]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3D[0, 1, 1])

5


**Negative Indexing**

In [42]:
print(arr3D[-1, -1, -1])

12


In [43]:
print(arr3D[-2, -2, -2])

2


#### Slicing arrays

1D array

In [45]:
arr1D = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr1D[:2])

[1 2]


In [46]:
print(arr1D[3:])

[4 5 6 7]


In [47]:
print(arr1D[1:3])

[2 3]


In [48]:
print(arr1D[1:5:2])

[2 4]


In [49]:
print(arr1D[::2])

[1 3 5 7]


2D array

In [50]:
arr2D = np.array([[1, 2, 3, 4, 5], [4, 5, 6, 7, 8]])
print(arr2D[1, 1:3])

[5 6]


In [51]:
print(arr2D[:, 2])

[3 6]


In [52]:
print(arr2D[:, 1:4])

[[2 3 4]
 [5 6 7]]


**Negative Slicing**

In [53]:
print(arr2D[0, -3:-1])

[3 4]


In [54]:
print(arr2D[-1, -4:-2])

[5 6]


**STEP**

In [55]:
print(arr2D[:, 1:4:2])

[[2 4]
 [5 7]]


In [56]:
print(arr2D[:, ::2])

[[1 3 5]
 [4 6 8]]
