# Data types

In [1]:
import numpy as np

*Create 1D array with integers*

In [5]:
arr = np.array([1, 2, 3, 4])

**Get the data type of an array object:**

In [14]:
print(arr.dtype)

int32


*Create a 1D array with strings*

In [15]:
arr_str = np.array(['apple', 'banana', 'carrot'])

**Get the data type of an array object:**

In [16]:
print(arr_str.dtype)

<U6


*Change the length of one word in array*

In [17]:
arr_str = np.array(['apple', 'banana', 'raspberries'])

*check the data type again*

In [11]:
print(arr_str.dtype)

<U11


## Creating Arrays With a Defined Data Type

In [19]:
arrS = np.array([1, 2, 3, 4], dtype='S')
print(arrS)
print(arrS.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [20]:
arrI = np.array([1, 2, 3, 4], dtype='i4')

print(arrI)
print(arrI.dtype)

[1 2 3 4]
int32


### Converting Data Type on Existing Arrays

In [22]:
arr_i = np.array([1.1, 2.1, 3.1])

newarr = arr_i.astype('i')

print(arr_i.dtype)
print(newarr)
print(newarr.dtype)

float64
[1 2 3]
int32


**Change data type from float to integer by using int as parameter value:**

In [23]:
newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3 4]
int32


*Change data type from integer to boolean:*

In [25]:
arrb = np.array([1, 0, 3])

newarrb = arrb.astype(bool)

print(arrb)
print(arrb.dtype)
print(newarrb)
print(newarrb.dtype)

[1 0 3]
int32
[ True False  True]
bool
