In [1]:
import numpy as np

## NumPy Array Shape and Reshape

In [15]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

**Get the Shape of an Array**

In [16]:
print(arr.shape)

(2, 4)


**Create an array with 3 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:**

In [19]:
arr3D = np.array([1, 2, 3, 4], ndmin=3)

print(arr3D)
print('shape of array :', arr3D.shape)

[[[1 2 3 4]]]
shape of array : (1, 1, 4)


**Reshape From 3-D to 4-D**

In [27]:
newarr = arr3D.reshape(1, 1, 2, 2)
print(newarr)
print(newarr.ndim)

[[[[1 2]
   [3 4]]]]
4


**Reshape From 3-D to 2-D**

In [28]:
newarr = arr3D.reshape(1, 4)
print(newarr)
print(newarr.ndim)

[[1 2 3 4]]
2


**Reshape from 3-D to 1-D**

In [29]:
newarr = arr3D.reshape(-2)
print(newarr)
print(newarr.ndim)

[1 2 3 4]
1


**Reshape From 1-D to 3-D**

In [32]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 2, 3)

print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


**Try converting 1D array with 8 elements to a 2D array with 3 elements in each dimension (will raise an error):**

In [37]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, 2)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


**Returns Copy or View?**

*Check if the returned array is a copy or a view:*

In [38]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


**Convert 1D array with 8 elements to 3D array with 2x2 elements:**

In [43]:
newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


**Flattening the arrays**

*Flattening array means converting a multidimensional array into a 1D array.*

In [59]:
arr = np.array([1, 2, 3], ndmin = 5)

newarr = arr.reshape(-1)

print(newarr)
print(newarr.ndim)

[1 2 3]
1
